### ISSUE TITLE
Tag latest version

### ISSUE THREAD

**Issue by twolfson** [simsalabim/sisyphus#119]
The latest releases of `sisyphus` have not been tagged in `git`. `bower` installs based off `git tags` and as a result, only `1.1.103` can be found. Can we please add some `git tag's` for the latest and past verisons?

**Comment by simsalabim** [comment]
Tagged the [latest](https://github.com/simsalabim/sisyphus/tree/v1.1.2) version.
<sup>Given that most of the past versions were patch updates, normally you want to use the most recent 1.1.**2**</sup><br/>
`bower install "sisyphus#1.1.2"` does the trick.

**Comment by twolfson** [comment]
Awesome, thanks =)
