### ISSUE TITLE
Rename package.json and publish to npm

### ISSUE THREAD

**Issue by twolfson** [simsalabim/sisyphus#120]
While this repository has a `package.json`, it is not published on `npm`. Instead, there is another package under the name of `sisyphus`. Maybe we should update the `package.json` to use `sisyphus.js` or something like that? Then, can we publish to `npm`?

https://www.npmjs.com/package/sisyphus

**Comment by simsalabim** [comment]
Thanks for pointing this out! [Done](https://www.npmjs.com/package/sisyphus.js)

**Comment by twolfson** [comment]
Woot, thanks =D
