### ISSUE TITLE
Can't make textareas to work

### ISSUE THREAD

**Issue by pedrocury** [simsalabim/sisyphus#127]
Hi,

I installed the plugin, by just including the minimized version in the end of my scripts. I use bootstrap 2.3, with some of other scripts... modals, tooltips, popovers, etc. Also use select2 version 2.x.

It works with input fields and checkboxes, but not with selects and textareas. So I started to take scripts out to check If could be a compatibility issue. Found that select2 has a incompatibity, cause it worked without it... but what I couldn't find a solution are the textareas and they are the most important for me.

They have id's and names. I tried to take control tags out and also coping the example HTML. Didn't work. Tried in IE, Chrome and Firefox.

Is there any known issues with bootstrap 2.3 ? Like the order of script loading or something ? 

Cheers

**Comment by simsalabim** [comment]
> Is there any known issues with bootstrap 2.3

Nothing that I'd be aware of. In theory, they shouldn't interfere at all, because sisyphus grabs bare html form data and doesn't do anything with how the data is presented on page (which bootstrap takes care of). 

If you find what exactly the issue was, please let me know. Thanks!

**Comment by pedrocury** [comment]
Thanks for the fast reply.

I tried to strip even more my script with no succes. If you like to take a look, it's here:
http://www.pedal.com.br/work/2015_simple_adm-textos-chama-inserir.asp - Simple version
http://www.pedal.com.br/work/2015_adm-textos-chama-inserir.asp - full script

I'll keep trying...

Cheers

**Comment by pedrocury** [comment]
Got it... 

It's something in the HTML inside the form...  Could make it work in the http://www.pedal.com.br/work/2015_adm-textos-chama-inserir.asp just changing the textarea from one div to another... but could not yet find out why... will try to find it out.  This new version is working in http://www.pedal.com.br/work/2015_simple4_adm-textos-chama-inserir.asp 

If I find it out, I let you know here...

Thanks!

**Comment by simsalabim** [comment]
> http://www.pedal.com.br/work/2015_simple_adm-textos-chama-inserir.asp - Simple version

Textarea there is not a part of form. Form elements must be inside `<form>` tag.

**Comment by pedrocury** [comment]
Actually the  </fieldset></form>  is after the textarea. But I'm using tabs, divs and so on... so I think I'm missing something in the HTML markup...  I used the same code, but with no tabs and no colum separation with divs and it worked... I will find out today... Cheers

**Comment by simsalabim** [comment]
@pedrocury what I meant is that `textarea` must live inside `form` tag in the markup.
```html
<form ....>
  ...
  <textarea></textarea>
</form>
```

**Comment by pedrocury** [comment]
It is...  but there's a lot of divs and other tags in between...

**Comment by simsalabim** [comment]
No, it's not
![screen shot 2015-06-29 at 11 37 59 am](https://cloud.githubusercontent.com/assets/53946/8413044/671ca7ae-1e53-11e5-9c7e-811b3180f409.png)
Please check the markup thoroughly.

**Comment by pedrocury** [comment]
God... you are right! But... something weird here... If I go to the console like you did I can see exactly the image you post... but If I go for the source code I see the </form> after the textarea, after the   comment!  This is kind of weird to me!

Well, I'm probably missing something, but it's not the plugin fault.  

Thank you for all help

![print](https://cloud.githubusercontent.com/assets/5623293/8489330/dd9e2d68-20f0-11e5-8b5c-add12c5fbde1.jpg)

**Comment by simsalabim** [comment]
I would suggest you reformatting html markup you wrote so you could clearly see nested elements. From what you've shown there is no way to tell where `<form>` tag was open and what other elements are nested from.
```xml
<form>
  <another_tag></another_tag>
  <one>
    <more>
      <tag>
        my text
      </tag>
    </more>
  </one>
</form>
```

**Comment by pedrocury** [comment]
Yep. The problem is when I have large forms, spread in different grid columns and tabs. I will take a deep look.

Thanks once again
