### ISSUE TITLE
Sysphus is not working with Chrome

### ISSUE THREAD

**Issue by shivrajsa** [simsalabim/sisyphus#132]
Below is my code & its not working with Chrome Version 46.0.2490.80 m.
Its working perfectly with Firefox, any suggestions.

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <script src="../jquery-1.11.1.min.js"></script>
    <script src="../sisyphus.min.js"></script>
    <script>
    $(window).load(function() { $("form").sisyphus({
    timeout:1
    });
    });
    </script>
    </head>
    <body>
    <form>
	<textarea rows="25" cols="159"></textarea>
    </form>
    </body>
    </html>

**Comment by simsalabim** [comment]
@shivrajsa please check samples on the [demo page](http://sisyphus-js.herokuapp.com/). Form fields must have some identifying information so the plugin could save data: names and/or ids. Normally, each html form element is supposed to have `name` attribute. This is how form data is submitted to the server.
