### ISSUE TITLE
$('form').sisyphus() not working in a form directive in angular js

### ISSUE THREAD

**Issue by nitish24p** [simsalabim/sisyphus#137]
var AnswerFormDirective = function(QuestionsService,AJAXCallService){
	return{
		restrict: 'E',
		scope:{
			guidelines: '@',
			imageUploading: '@',
			answerFormId: '@'
		},
		templateUrl: '../consult/assets/src/views/answerForm.html',
		controller: function($scope,$stateParams,$resource,$location, appvalues){
			//$scope.answer = '';
			var form = $('form');
			var formId = $("#answer-form").attr('form-id');
			console.log(formId);
			$('form').sisyphus();
                 }
}

i have a directive which is  the text area with a submit button. I can see the text entering in the localstorage however when i refresh the page the data is lost. Doesnt get persisted. PS: the shared code is snippet, so ignore any incomplete brackets.

**Comment by simsalabim** [comment]
@nitish24p did you find a solution?

**Comment by nitish24p** [comment]
nopes wrote a workaround on my own without the sisyphus library
