### ISSUE TITLE
Unbind a form when using ajax

### ISSUE THREAD

**Issue by diofeher** [simsalabim/sisyphus#37]
Hello!
I want to unbind a form from sisyphus because the site I'm coding uses ajax in a lot of places. What is happening:

1 - I'm binding sisyphus to form
self.sisyphus = $('form').sisyphus();

2 - The form is sent by ajax so in the ajax call I use:
self.sisyphus.manuallyReleaseData();

The tricky part is here, because the method is called, but after this, saveDataTimeout is called again, so the form is sent again!

What should I do?

**Comment by edilecachan** [comment]
Hello,

Was this issue solved ?

Yours,
