### ISSUE TITLE
Adapt plugin to work with TinyMCE.

### ISSUE THREAD

**Issue by simsalabim** [simsalabim/sisyphus#4]
CKEditor out-of-the-box support added in v1.1.1

**Comment by andresteves** [comment]
CKEditor not working anymore

**Comment by simsalabim** [comment]
As much as I love the above comment, it's irrelevant to the topic.

**Comment by andresteves** [comment]
Then seems all comments in this topic are irrelevant right? No problem I will try and share any findings wih the community...

Kind Regards,
Andre

**Comment by simsalabim** [comment]
Taking the convo to the relevant [issue](https://github.com/simsalabim/sisyphus/issues/149).
