### ISSUE TITLE
Fields dynamically added to a form once it is protected are not saved, even if protect() is called again

### ISSUE THREAD

**Issue by nschneid** [simsalabim/sisyphus#47]
I think the issue is with this code in `protect()`:

``` js
if ( ! params.started ) {
  self.bindSaveData();
  params.started = true;
}
```

`bindSaveData()` is only called the first time `sisyphus()` is invoked. What is the rationale for this check?

**Comment by unguul** [comment]
@nschneid I ran into a similar issue with a form with fields that are dynamically generated (on user action). Calling `bindSaveData()` on the` sisyphus`ed instance of my form fixed the issue for me.
