### ISSUE TITLE
AutoRelase / manuallyReleaseData

### ISSUE THREAD

**Issue by Ahnungsloser** [simsalabim/sisyphus#86]
Hi all, I´m new to Sisyphus and jQuery.
I have integrated it to my site. My Form is checked by PHP for mistake, the data is written to MYSQL and the user is redirected to a confirmation site. Now my question. I have added following code to my form site ...

$( function() {
$( \"#formdata\" ).sisyphus({
    autoRelease: false
    });
} );
</script>

Input is correct, checked by PHP and user is redirected. How can I clear the data now from the new site ...

I tried $('#formdata').sisyphus.manuallyReleaseData();
but seems not to be workin. Any help for a newbie is apreciated.

**Comment by SangeethaSiva** [comment]
Hi,
I want my form data need to be released once the form is submitted. 
We have this line - autoRelease: true.
But data is not cleared after submit. Can you please guide?
