### ISSUE TITLE
Integration with redactorJS

### ISSUE THREAD

**Issue by carlostubff** [simsalabim/sisyphus#90]
Hi, there's some implementation for redactorJS?
Redactor is a  WYSIWYG for textareas
Here's the link: http://imperavi.com/redactor/
thanks

**Comment by lptn** [comment]
@carlostubff 

I know it's too late, but you can use the code:
```javascript
$('form').sisyphus({
           onRestore: function() {
              $('textarea').redactor();
             }
});
```
